apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  name: INSERT-BUILD-NAME-HERE
spec:
  nodeSelector: null
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: "#!groovy\npipeline \n{\n  agent any    \n    \n  stages \n  {\n
        \   stage('initialise') \n    {\n      agent any\n      steps \n      {\n
        \       echo \"Running Pipeline....\"\n        sh \"oc version\"\n        sh
        'printenv'\n      }\n    }\n  }\n}\n"
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
